platform :ios, ‘7.0’

pod 'SDWebImage', '~> 3.7.5'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.0'
pod 'AVOSCloud', '~> 3.2.8'
pod 'AVOSCloudIM', '~> 3.2.8'